# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: |
  (?x)^(
    .*tests/fixtures/.+|
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["-f=lf"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.4.3"
    hooks:
      - id: ruff
        args: ["--fix", "--preview"]
      - id: ruff-format
        args: ["--preview"]

  # documentation
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.9.1
    hooks:
      - id: sphinx-lint
        args: [--enable=default-role]
  - repo: https://github.com/dzhu/rstfmt
    rev: v0.0.14
    hooks:
      - id: rstfmt
        args: ["-w", "-1"]
        files: \.rst$

  # git commit
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.8.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
        args:
          ["--types=chore,change,ci,docs,feat,fix,refactor,remove,revert,bump"]
