[tool.commitizen]
name = "cz_conventional_commits"
version = "1.8.1"
tag_format = "v$version"
version_files = [
    "pytest-embedded/pytest_embedded/__init__.py",
    "pytest-embedded/pyproject.toml",
    "pytest-embedded-arduino/pytest_embedded_arduino/__init__.py",
    "pytest-embedded-arduino/pyproject.toml",
    "pytest-embedded-idf/pytest_embedded_idf/__init__.py",
    "pytest-embedded-idf/pyproject.toml",
    "pytest-embedded-jtag/pytest_embedded_jtag/__init__.py",
    "pytest-embedded-jtag/pyproject.toml",
    "pytest-embedded-qemu/pytest_embedded_qemu/__init__.py",
    "pytest-embedded-qemu/pyproject.toml",
    "pytest-embedded-serial/pytest_embedded_serial/__init__.py",
    "pytest-embedded-serial/pyproject.toml",
    "pytest-embedded-serial-esp/pytest_embedded_serial_esp/__init__.py",
    "pytest-embedded-serial-esp/pyproject.toml",
    "pytest-embedded-wokwi/pytest_embedded_wokwi/__init__.py",
    "pytest-embedded-wokwi/pyproject.toml",
]

[tool.isort]
profile = 'black'

[tool.black]
line-length = 120
target-version = ['py37']
force-exclude = '/tests/'
skip-string-normalization = true

[tool.ruff]
select = [
    'F',  # Pyflakes
    'E',  # pycodestyle
    'W',  # pycodestyle
#    'C90',  # mccabe
#    'I',  # isort
#    'N',  # pep8-naming
#    'D',  # pydocstyle
#    'UP',  #  pyupgrade
#    'YTT',  # flake8-2020
#    'ANN',  # flake8-annotations
#    'S',  # flake8-bandit
#    'BLE',  # flake8-blind-except
#    'FBT',  # flake8-boolean-trap
#    'B',  # flake8-bugbear
#    'A',  # flake8-builtins
#    'COM',  # flake8-commas
#    'C4',  #  flake8-comprehensions
#    'DTZ',  # flake8-datetimez
#    'T10',  # flake8-debugger
#    'DJ',  #  flake8-django
#    'EM',  #  flake8-errmsg
#    'EXE',  # flake8-executable
#    'ISC',  # flake8-implicit-str-concat
#    'ICN',  # flake8-import-conventions
#    'G',  # flake8-logging-format
#    'INP',  # flake8-no-pep420
#    'PIE',  # flake8-pie
#    'T20',  # flake8-print
#    'PYI',  # flake8-pyi
#    'PT',  #  flake8-pytest-style
#    'Q',  # flake8-quotes
#    'RSE',  # flake8-raise
#    'RET',  # flake8-return
#    'SLF',  # flake8-self
#    'SIM',  # flake8-simplify
#    'TID',  # flake8-tidy-imports
#    'TCH',  # flake8-type-checking
#    'ARG',  # flake8-unused-arguments
#    'PTH',  # flake8-use-pathlib
#    'ERA',  # eradicate
#    'PD',  #  pandas-vet
#    'PGH',  # pygrep-hooks
#    'PL',  #  Pylint
#    'TRY',  # tryceratops
#    'NPY',  # NumPy-specific rules
#    'RUF',  # Ruff-specific rules
]
line-length = 120
target-version = "py37"

[tool.pytest.ini_options]
norecursedirs = 'examples/*'
addopts = "-s"
